# Generated by Django 3.1.2 on 2021-02-08 22:58

from django.db import migrations, models
import profiles.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210101_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to=profiles.utils.userAvatarPath),
        ),
    ]
